name: "FoD Setup Release"
description: "Make sure a FoD release is defined and configured and create it if not"
inputs:
  ssc_app_name:
    required: true
    description: "SSC Application Name"
  ssc_appversion_name:
    required: true
    description: "SSC Application Version Name"
  ssc_url:
    required: true
    description: "SSC URI"
  ssc_token:
    required: true
    description: "SSC CI Token"
outputs:
  release_id:
    description: "SSC AppVersion Id"
    value: ${{ steps.create-appversion.outputs.appversion_id }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Fetch at least the immediate parents so that if this is a pull request then we can checkout the head.
        fetch-depth: 2
        
    # Java is required to run the various Fortify utilities.
    # Setup JDK 17 on host
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    # Install Fortify tools
    - name: Setup Fortify tools
      uses: fortify/github-action/setup@v1
      with:
        export-path: true
        fcli: latest
        sc-client: skip
        fod-uploader: skip
        vuln-exporter: skip
        bugtracker-utility: skip
        
    # Login to SSC
    - name: Login
      shell: bash
      run: |
        fcli ssc session login --url $SSC_URI -t $SSC_TOKEN --session github-actions
        # Bug - we need a default session for actions to work currently, delete below and uncomment above when working
        #fcli ssc session login --url $SSC_URI -t $SSC_TOKEN -k
      env:
        SSC_URI: ${{ inputs.ssc_url }}
        SSC_TOKEN: ${{ inputs.ssc_token }}
        
    # Create a new Fortify SSC Application Version for GitHub branch
    - name: Create SSC Application Version
      id: create-appversion
      shell: bash
      run: |
        fcli ssc av list -q "application.name=='$SSC_APP_NAME'" --session github-actions
        echo fcli ssc av create "${SSC_APP_NAME}:${SSC_APPVER_NAME}" --description "Created automatically from GitHub" --auto-required-attrs --skip-if-exists -o expr="{id}" --session github-actions
        APPVER_ID=$(fcli ssc av create "${SSC_APP_NAME}:${SSC_APPVER_NAME}" --description "Created automatically from GitHub" --auto-required-attrs --skip-if-exists -o expr="{id}" --session github-actions)
        echo "::debug::Created/Using appversion_id=${APPVER_ID}"
        echo "appversion_id=${APPVER_ID}" >> $GITHUB_OUTPUT
      id: create_ssc_release
      env:
        SSC_APP_NAME: ${{ inputs.ssc_app_name }}
        SSC_APPVER_NAME: ${{ inputs.ssc_appver_name }}
    
    # Logout/Close SSC session
    - name: Logout fcli
      shell: bash
      run: |
        fcli ssc session logout --no-revoke-token --session github-actions
        

