name: "ScanCentral DAST Scan"
description: "Runs a ScanCentral DAST Scan"
inputs:
  ssc_url:
    required: true
    description: "SSC URI"
  ssc_token:
    required: true
    description: "SSC CI Token"
  scan_settings_id:
    required: true
    description: "ScanCentral DAST Scan Settings Id"
  scan_name:
    required: false
    description: "The name of the scan (displayed in UI)"
    default: "GitHub Actions Initiated DAST Scan"
  do_wait:
    required: false
    description: "Whether to wait for the scan to finish or not"
    default: "false"
outputs:
  scdast_scan_id:
    description: "ScanCentral DAST Scan Id"
    value: ${{ steps.scdast-scan.outputs.scdast_scan_id }}
runs:
  using: "composite"
  steps:
    # Java is required to run the various Fortify utilities.
    # Setup JDK 11 on host
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    # Install Fortify tools
    - name: Setup Fortify tools
      uses: fortify/github-action/setup@v1
      with:
        export-path: true
        fcli: latest
    # Login to ScanCentral DAST fcli session
    - name: Login
      shell: bash
      run: |
        fcli sc-dast session login --ssc-url $SSC_URI -t $SSC_TOKEN --ssc-session github-actions
      env:
        SSC_URI: ${{ inputs.ssc_url }}
        SSC_TOKEN: ${{ inputs.ssc_token }}
    # Start ScanCentral DAST scan and optionally wait until results complete.
    - name: Perform ScanCentral DAST scan
      id: scdast-scan
      shell: bash
      run: |
        fcli sc-dast scan start -n "$SCAN_NAME" -s $SETTINGS_ID --store curScan --ssc-session github-actions
        echo "scdast_scan_id=$(fcli util var get ::curScan::)" >> $GITHUB_OUTPUT
        if [ $DO_WAIT ]
        then
            fcli sc-dast scan wait-for ::curScan:: --ssc-session github-actions
        fi    
      env:
        SCAN_NAME: ${{ inputs.scan_name }}
        SETTINGS_ID: ${{ inputs.scan_settings_id }}
        DO_WAIT: ${{ inputs.do_wait }}
    # Logout/Close ScanCentral DAST fcli session
    - name: Logout
      shell: bash
      run: |
        fcli sc-dast session logout --no-revoke-token --ssc-session github-actions
