name: "Verify FoD Security Policy"
description: "Verify that the security policy in Fortify on Demand has been met for the release"
inputs:
  fod_api_url:
    required: false
    description: "FoD API URL"
    default: "https://api.ams.fortify.com"
  fod_client_id:
    required: true
    description: "FoD API Client Id"
  fod_client_secret:
    required: true
    description: "FoD API Client Secret"
  fod_app_name:
    required: true
    description: "FoD Application Name"
  fod_release_name:
    required: true
    description: "FoD Release Name"
runs:
  using: "composite"
  steps:
    # Java is required to run the various Fortify utilities.
    # Setup JDK 11 on host
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    # Install Fortify tools
    - name: Setup Fortify tools
      uses: fortify/github-action/setup@v1
      with:
        export-path: true
        fcli: latest
    # Login to Fortify on Demand fcli session
    - name: Login fcli
      shell: bash
      run: |
        fcli fod session login --url $FOD_API_URL --client-id $FOD_CLIENT_ID --client-secret $FOD_CLIENT_SECRET --fod-session github-actions
      env:
        FOD_API_URL: ${{ inputs.fod_api_url }}
        FOD_CLIENT_ID: ${{ inputs.fod_client_id }}
        FOD_CLIENT_SECRET: ${{ inputs.fod_client_secret }}
    # Check Security Policy of the Fortify on Demand Release to determine success/failure
    - name: Verify Security Policy
      id: verify-security-policy
      continue-on-error: true
      shell: bash
      run: |
        fcli fod action run release-summary --release "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" --fod-session github-actions >> $GITHUB_STEP_SUMMARY
        fcli fod action run check-policy --release "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" --fod-session github-actions
      env: 
        FOD_APP_NAME: ${{ inputs.fod_app_name }}
        FOD_RELEASE_NAME: ${{ inputs.fod_release_name }}
    # Logout/Close Fortify on Demand fcli session
    - name: Logout fcli
      shell: bash
      run: |
        fcli fod session logout --fod-session github-actions
